
version: '3'

services:
  # Frontend React App
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api
      - VITE_ADMIN_SECRET_CODE=Butord098#
    depends_on:
      - backend
    networks:
      - app-network

  # Backend PHP Server
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:80"
    volumes:
      - ./src/api:/var/www/html/api
      - ./secrets:/var/www/secrets
    environment:
      - DB_HOST=database
      - DB_NAME=your_database
      - DB_USER=root
      - DB_PASS=rootpassword
      - CORS_ALLOW_ORIGIN=http://localhost:8080
    depends_on:
      - database
    networks:
      - app-network

  # MySQL Database
  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=your_database
    volumes:
      - ./src/api/database.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
